version: "3.8"
name: tiktok_project
services:
  tiktok_mssql_db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: tiktok_mssql_db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}
    restart: always
    ports:
      - "1435:1433"
    volumes:
      - tiktok_mssql_db_data:/var/lib/sqlserver/data
    
  tiktok_mongo_db:
    image: mongo:latest
    container_name: tiktok_mongo_db
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - tiktok_mongo_db_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      
  tiktok_redis:
    image: redis:alpine
    container_name: tiktok_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - tiktok_redis_data:/data
    command: /bin/sh -c "redis-server --requirepass ${DB_PASSWORD}"
    

networks:
  default:
    name: tiktok_network
    driver: bridge

volumes: 
    tiktok_mssql_db_data:
        name: tiktok_mssql_db_data
    tiktok_mongo_db_data:
        name: tiktok_mongo_db_data
    tiktok_redis_data:
        name: tiktok_redis_data